[build]
  command = "npm install --legacy-peer-deps && npm run build"
  publish = "dist/todo-list-app/browser"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "20"
